import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { cormorant, jost } from "@/lib/fonts";
import Header from "@/src/core/interface/components/organisms/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        cormorant.variable,
        jost.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
